QBShared = QBShared or {}
QBShared.Gangs = {
    civil = { label = 'Civil', grades = { { name = 'Sans Affiliation' } } },
    miamiboyz = {
        label = 'Miami Boyz',
        grades = {
            { name = 'Habitant' },
            { name = 'Homies' },
            { name = 'Gangsta' },
            { name = 'Hustler' },
            { name = 'Big Hustler' },
            { name = 'Triple OG', isboss = true },
            { name = 'Double OG', isboss = true },
            { name = 'OG', isboss = true },
        },
    },
    braithemb = {
        label = 'Braithem B',
        grades = {
            { name = 'Private E-1' },
            { name = 'Private E-2' },
            { name = 'Caporal' },
            { name = 'Sergent' },
            { name = '1er Lieutenant' },
            { name = 'Capitaine', isboss = true },
            { name = 'Major', isboss = true },
        },
    },
    hoovers = {
        label = 'Hoovers',
        grades = {
            { name = 'Petit' },
            { name = 'Aster' },
            { name = 'Cuz' },
            { name = 'Second', isboss = true },
            { name = 'OG', isboss = true },
        },
    },
    losvalentinos = {
        label = 'Los Valentinos',
        grades = {
            { name = 'Parasite' },
            { name = 'Postulant' },
            { name = 'Membre Honoraire' },
            { name = 'Membre Attitré' },
            { name = '1ère Classe' },
            { name = 'Caporal' },
            { name = 'Sergent d\'Armes' },
            { name = 'Trésorier' },
            { name = 'Secrétaire', isboss = true },
            { name = 'Vice-Président', isboss = true },
            { name = 'Président', isboss = true },
        },
    },
    piru = {
        label = 'Piru Streetboys',
        grades = {
            { name = 'Petit' },
            { name = 'Moyen' },
            { name = 'Grand' },
            { name = 'Bras Droit', isboss = true },
            { name = 'OG', isboss = true },
        },
    },
    nemesis = {
        label = 'Némésis',
        grades = {
            { name = 'Aspirant' },
            { name = 'Associé' },
            { name = 'Second', isboss = true },
            { name = 'Conseiller', isboss = true },
            { name = 'Padre', isboss = true },
        },
    },
    fuerzaespinoza = {
        label = 'Fuerza Espinoza',
        grades = {
            { name = 'Teniente' },
            { name = 'Segundo' },
            { name = 'Commandante', isboss = true },
            { name = 'Jefe', isboss = true },
        },
    },
    endofwatch = {
        label = 'End Of Watch',
        grades = {
            { name = 'Recrue' },
            { name = 'Homme de Main' },
            { name = 'Représentant' },
            { name = 'Lieutenant', isboss = true },
            { name = 'Capitaine', isboss = true },
            { name = 'Leader', isboss = true },
        },
    },
    casano = {
        label = 'Clan Casano',
        grades = {
            { name = 'Chauffeur' },
            { name = 'Soldat' },
            { name = 'Guarde Rapprochée' },
            { name = 'Conseiller' },
            { name = 'Ambassadrice' },
            { name = 'Gérant', isboss = true },
            { name = 'Chef', isboss = true },
        },
    },
    triade = {
        label = 'Triade Xin Yi An',
        grades = {
            { name = 'Membre' },
            { name = 'Officier d\'Execution' },
            { name = 'Officier Général' },
            { name = 'Officier d\'Administration' },
            { name = 'Officier des Liaisons' },
            { name = 'Maitre des Opérations' },
            { name = 'Maitre des Cérémonies' },
            { name = 'Seconde Tête', isboss = true },
            { name = 'Tête de Dragon', isboss = true },
        },
    },
    bmf = {
        label = 'BMF',
        grades = {
            { name = 'Recrue' },
            { name = 'Homme de Main' },
            { name = 'Gangster' },
            { name = 'Lieutenant' },
            { name = 'Second', isboss = true },
            { name = 'Boss', isboss = true },
        },
    },
    irishbearded = {
        label = 'Irish Bearded Original Grade',
        grades = {
            { name = 'Support' },
            { name = 'Propspect' },
            { name = 'Membre' },
            { name = 'Road Captain' },
            { name = 'Enforcer' },
            { name = 'Treasurer' },
            { name = 'Advistor' },
            { name = 'Secretary' },
            { name = 'Sgt At Arms' },
            { name = 'Vice-président', isboss = true },
            { name = 'Président', isboss = true },
        },
    },
    cosanostra = {
        label = 'Cosa Nostra',
        grades = {
            { name = 'Soldat' },
            { name = 'Caporal' },
            { name = 'Sergent' },
            { name = 'Major' },
            { name = 'Bras Droit', isboss = true },
            { name = 'Don', isboss = true },
        },
    },
    vagos = {
        label = 'Vagos',
        grades = {
            { name = 'Pequeno' },
            { name = 'Soldado' },
            { name = 'Commandante' },
            { name = 'Teniente' },
            { name = 'Segundo', isboss = true },
            { name = 'Jefe', isboss = true },
        },
    },
    mob = {
        label = 'MOB',
        grades = {
            { name = 'Young Boy' },
            { name = 'Boy' },
            { name = 'Youg Gangster' },
            { name = 'Gangster' },
            { name = 'Head', isboss = true },
            { name = 'Big Head', isboss = true },
        },
    },
    pcc = {
        label = 'Primeiro Comando da Capital',
        grades = {
            { name = 'Pequeno' },
            { name = 'Soldado' },
            { name = 'Commandante' },
            { name = 'Teniente' },
            { name = 'Segundo', isboss = true },
            { name = 'Jefe', isboss = true },
        },
    },
    lco = {
        label = 'LCO',
        grades = {
            { name = 'Recrue' },
            { name = 'Membre', isboss = true },
        },
    },
    hargreeves = {
        label = 'Famille Hargreeves',
        grades = {
            { name = 'Membre', isboss = true },
        },
    },
    nightkidz = {
        label = 'Night Kidz',
        grades = {
            { name = 'Recrue' },
            { name = 'Membre' },
            { name = 'Second', isboss = true },
            { name = 'Chef', isboss = true },
        },
    },
    kcorp = {
        label = 'Kcorp',
        grades = {
            { name = 'Membre', isboss = true },
        },
    },
    crips = {
        label = 'Crips',
        grades = {
            { name = 'Homies' },
            { name = 'Gangsta' },
            { name = 'R.G' },
            { name = 'Y.G' },
            { name = 'O.G', isboss = true },
        },
    },
    latinscorpion = {
        label = 'Latin Scorpion',
        grades = {
            { name = 'Habitante' },
            { name = 'Pequeno' },
            { name = 'Grande', isboss = true },
        },
    },
    cjng = {
        label = 'Cartel Jalisco Nouvelle Generation',
        grades = {
            { name = 'Narcomenuedistas' },
            { name = 'Miembro de Plaza' },
            { name = 'Sicario' },
            { name = 'Teniente' },
            { name = 'Jefes de Sicarios' },
            { name = 'Lideres de Plaza', isboss = true },
            { name = 'Capo Los Santos Country', isboss = true },
            { name = 'Capo Blaine County', isboss = true },
            { name = 'Comandantes', isboss = true },
            { name = 'Jefe del Territorio', isboss = true },
        },
    },
    ttk = {
        label = 'Train To Kill',
        grades = {
            { name = 'Lil\' Guy' },
            { name = 'Gangster' },
            { name = 'Hustler' },
            { name = 'OG', isboss = true },
            { name = 'Underboss', isboss = true },
            { name = 'Boss', isboss = true },
        },
    },
    dsr = {
        label = 'Dark Street Runners',
        grades = {
            { name = 'Urban Novice' },
            { name = 'Lunar Navigateur' },
            { name = 'Dark Mechanic' },
            { name = 'Eclipse Enforcer' },
            { name = 'Phantom Driver' },
            { name = 'Shadow Strategist' },
            { name = 'Night Co-Leader', isboss = true },
            { name = 'Night Leader', isboss = true },
        },
    },
    reapers = {
        label = 'Reapers',
        grades = {
            { name = 'Recrue' },
            { name = 'Homme de Main' },
            { name = 'Lieutenant' },
            { name = 'Conseiller' },
            { name = 'Caporal', isboss = true },
            { name = 'Second', isboss = true },
            { name = 'Boss', isboss = true },
        },
    },
    scavengers = {
        label = 'Scavengers',
        grades = {
            { name = 'Miteux' },
            { name = 'Charognard' },
            { name = 'Punk à Chien', isboss = true },
            { name = 'Le Roi des égouts', isboss = true },
        },
    },
    malvabundos = {
        label = 'Malvabundos',
        grades = {
            { name = 'Prospect' },
            { name = 'Membre' },
            { name = 'Road Captain' },
            { name = 'Trésorier' },
            { name = 'Secrétaire' },
            { name = 'Sgt At Arms' },
            { name = 'Vice-Président', isboss = true },
            { name = 'Président', isboss = true },
        },
    },
}
