QBShared = QBShared or {}
QBShared.Gangs = {
    civil = { label = 'Civil', grades = { { name = 'Sans Affiliation' } } },

    --[[ miamiboyz = {
        label = 'Miami Boyz',
        grades = {
            { name = 'Habitant' },
            { name = 'Homies' },
            { name = 'Gangsta' },
            { name = 'Hustler' },
            { name = 'Big Hustler' },
            { name = 'Triple OG', isboss = true },
            { name = 'Double OG', isboss = true },
            { name = 'OG', isboss = true },
        },
    },
    nemesis = {
        label = 'Némésis',
        grades = {
            { name = 'Aspirant' },
            { name = 'Associé' },
            { name = 'Second', isboss = true },
            { name = 'Conseiller', isboss = true },
            { name = 'Padre', isboss = true },
        },
    },
    fuerzaespinoza = {
        label = 'Fuerza Espinoza',
        grades = {
            { name = 'Teniente' },
            { name = 'Segundo' },
            { name = 'Commandante', isboss = true },
            { name = 'Jefe', isboss = true },
        },
    },
    endofwatch = {
        label = 'End Of Watch',
        grades = {
            { name = 'Recrue' },
            { name = 'Homme de Main' },
            { name = 'Représentant' },
            { name = 'Lieutenant', isboss = true },
            { name = 'Capitaine', isboss = true },
            { name = 'Leader', isboss = true },
        },
    },
    lapiovra = {
        label = 'La Piovra',
        grades = {
            { name = 'Tentacule Visible' },
            { name = 'Tentacule Invisible' },
            { name = 'Leader', isboss = true },
        },
    },
    triade = {
        label = 'Triade Xin Yi An',
        grades = {
            { name = 'Membre' },
            { name = 'Officier d\'Execution' },
            { name = 'Officier Général' },
            { name = 'Officier d\'Administration' },
            { name = 'Officier des Liaisons' },
            { name = 'Maitre des Opérations' },
            { name = 'Maitre des Cérémonies' },
            { name = 'Seconde Tête', isboss = true },
            { name = 'Tête de Dragon', isboss = true },
        },
    },
    braithemb = {
        label = 'Braithem B',
        grades = {
            { name = 'Private E-1' },
            { name = 'Private E-2' },
            { name = 'Caporal' },
            { name = 'Sergent' },
            { name = '1er Lieutenant' },
            { name = 'Capitaine', isboss = true },
            { name = 'Major', isboss = true },
        },
    },
    cosanostra = {
        label = 'Cosa Nostra',
        grades = {
            { name = 'Picciollo' },
            { name = 'Soldado' },
            { name = 'Capo', isboss = true },
            { name = 'Consigliere', isboss = true },
            { name = 'Don', isboss = true },
        },
    },
    ms13 = {
        label = 'MS13',
        grades = {
            { name = 'Pequeno' },
            { name = 'Soldado' },
            { name = 'Grande' },
            { name = 'Sergendo' },
            { name = 'Mano Derecha', isboss = true },
            { name = 'Jefe/a', isboss = true },
        },
    },
    hargreeves = {
        label = 'Famille Hargreeves',
        grades = {
            { name = 'Membre', isboss = true },
        },
    },
    cjng = {
        label = 'Cartel Jalisco Nouvelle Generation',
        grades = {
            { name = 'Narcomenuedistas' },
            { name = 'Miembro de Plaza' },
            { name = 'Sicario' },
            { name = 'Teniente' },
            { name = 'Jefes de Sicarios' },
            { name = 'Lideres de Plaza', isboss = true },
            { name = 'Capo Los Santos Country', isboss = true },
            { name = 'Capo Blaine County', isboss = true },
            { name = 'Comandantes', isboss = true },
            { name = 'Jefe del Territorio', isboss = true },
        },
    },
    ttk = {
        label = 'Train To Kill',
        grades = {
            { name = 'Lil\' Guy' },
            { name = 'Gangster' },
            { name = 'Hustler' },
            { name = 'OG', isboss = true },
            { name = 'Underboss', isboss = true },
            { name = 'Boss', isboss = true },
        },
    },
    dsr = {
        label = 'Dark Street Runners',
        grades = {
            { name = 'Urban Novice' },
            { name = 'Lunar Navigateur' },
            { name = 'Dark Mechanic' },
            { name = 'Eclipse Enforcer' },
            { name = 'Phantom Driver' },
            { name = 'Shadow Strategist' },
            { name = 'Night Co-Leader', isboss = true },
            { name = 'Night Leader', isboss = true },
        },
    },
    reapers = {
        label = 'Reapers',
        grades = {
            { name = 'Recrue' },
            { name = 'Homme de Main' },
            { name = 'Lieutenant' },
            { name = 'Conseiller' },
            { name = 'Caporal', isboss = true },
            { name = 'Second', isboss = true },
            { name = 'Boss', isboss = true },
        },
    },
    latinscorpion = {
        label = 'Latin Scorpion',
        grades = {
            { name = 'Habitante' },
            { name = 'Pequeno' },
            { name = 'Grande', isboss = true },
        },
    },
    malvabundos = {
        label = 'Malvabundos',
        grades = {
            { name = 'Prospect' },
            { name = 'Membre' },
            { name = 'Road Captain' },
            { name = 'Trésorier' },
            { name = 'Secrétaire' },
            { name = 'Sgt At Arms' },
            { name = 'Vice-Président', isboss = true },
            { name = 'Président', isboss = true },
        },
    },
    verdugos = {
        label = 'Verdugos MC',
        grades = {
            { name = 'Support' },
            { name = 'Prospect' },
            { name = 'Tailgunner' },
            { name = 'Enforcer' },
            { name = 'Full Patch' },
            { name = 'Road Captain' },
            { name = 'Sergent d\'Armes' },
            { name = 'Trésorier' },
            { name = 'Vice-Président', isboss = true },
            { name = 'Président', isboss = true },
        },
    },
    ubc = {
        label = 'UBC',
        grades = {
            { name = 'Petit Nouveau' },
            { name = 'Membre Confirmé' },
            { name = 'Second', isboss = true },
            { name = 'Chef', isboss = true },
        },
    },
    lost = {
        label = 'The LOST MC',
        grades = {
            { name = 'Prospect' },
            { name = 'Membre' },
            { name = 'Représentant' },
            { name = 'Trésorier' },
            { name = 'Secrétaire' },
            { name = 'Sergent At Arms' },
            { name = 'Vice-Président', isboss = true },
            { name = 'Président', isboss = true },
        },
    },
    comptonwest = {
        label = 'Compton West',
        grades = {
            { name = 'Habitant' },
            { name = 'Rookie' },
            { name = 'Young Gangsta' },
            { name = 'Leader' },
            { name = 'Original Gangsta' },
            { name = 'Real Gangsta', isboss = true },
            { name = 'Old Gangsta', isboss = true },
            { name = 'Gangsta King', isboss = true },
        },
    },
    lossalvador = {
        label = 'Los Salvador',
        grades = {
            { name = 'Executant' },
            { name = 'Soldat' },
            { name = 'Chef de Régime' },
            { name = 'Bras Droit', isboss = true },
            { name = 'Consiglio', isboss = true },
            { name = 'Parrain', isboss = true },
        },
    },
    comando = {
        label = 'Comando Vermelho',
        grades = {
            { name = 'Novinho' },
            { name = 'Soldado' },
            { name = 'Favelado' },
            { name = 'Chef de Divisao' },
            { name = 'Terro' },
            { name = 'Chef Geral', isboss = true },
            { name = 'Braco Direito', isboss = true },
            { name = 'Chef', isboss = true },
        },
    },
    blackd = {
        label = 'Black Disciples',
        grades = {
            { name = 'Lil Gangsta' },
            { name = 'Gangsta' },
            { name = 'Hustler', isboss = true },
            { name = 'Original YG', isboss = true },
            { name = 'OG', isboss = true },
        },
    },
    crew = {
        label = 'Crew',
        grades = {
            { name = 'OG des OGM', isboss = true },
            { name = 'OG des Culs de Joints', isboss = true },
            { name = 'OG de la Boite à Gants', isboss = true },
            { name = 'OG des Cartons', isboss = true },
            { name = 'OG du Crack', isboss = true },
            { name = 'OG des Rats', isboss = true },
            { name = 'OG du Canapé', isboss = true },
        },
    },
    carrington = {
        label = 'Famille Carrington',
        grades = {
            { name = 'Sicarios' },
            { name = 'Teniente' },
            { name = 'Consejero', isboss = true },
            { name = 'Vice-Jefe', isboss = true },
            { name = 'Jefe', isboss = true },
        },
    },
    dnk = {
        label = 'Dark Night Killers',
        grades = {
            { name = 'Escouade D' },
            { name = 'Escouade C' },
            { name = 'Escouade B' },
            { name = 'Escouade A' },
            { name = 'Chef d\'Escouade', isboss = true },
            { name = 'Boss', isboss = true },
        },
    },
    yokai = {
        label = 'Yokai',
        grades = {
            { name = 'Shatei' },
            { name = 'Kyodai' },
            { name = 'Saiki-Komon', isboss = true },
            { name = 'Shatei-Gashira', isboss = true },
            { name = 'Waka-gashira', isboss = true },
            { name = 'Oyabun', isboss = true },
        },
    },
    piru = {
        label = 'Piru Streetboys',
        grades = {
            { name = 'Petit' },
            { name = 'Moyen' },
            { name = 'Grand' },
            { name = 'Bras Droit', isboss = true },
            { name = 'OG', isboss = true },
        },
    },
    brs = {
        label = 'BRS',
        grades = {
            { name = 'Little Gangsta' },
            { name = 'Gangsta' },
            { name = 'Big gangsta' },
            { name = 'Hustler', isboss = true },
            { name = 'YG', isboss = true },
            { name = 'OG', isboss = true },
        },
    },
    hoovers = {
        label = 'Hoovers',
        grades = {
            { name = 'Novato' },
            { name = 'La Madrina' },
            { name = 'Soldado' },
            { name = 'Peroguardian' },
            { name = 'Grande', isboss = true },
            { name = 'El Teniente', isboss = true },
            { name = 'El Segundo', isboss = true },
            { name = 'El Jefe', isboss = true },
        },
    },
    bhb = {
        label = 'BHB',
        grades = {
            { name = 'BHB' },
            { name = 'OG', isboss = true },
        },
    },
    oclock = {
        label = '12 O\'clock Boys',
        grades = {
            { name = 'Petit' },
            { name = 'Grand' },
            { name = 'Bras Droit', isboss = true },
            { name = 'Boss', isboss = true },
        },
    },
    losvalentinos = {
        label = 'Los Valentinos',
        grades = {
            { name = 'Parasite' },
            { name = 'Postulant' },
            { name = 'Membre Honoraire' },
            { name = 'Membre Attitré' },
            { name = '1ère Classe' },
            { name = 'Caporal' },
            { name = 'Sergent d\'Armes' },
            { name = 'Trésorier' },
            { name = 'Secrétaire', isboss = true },
            { name = 'Vice-Président', isboss = true },
            { name = 'Président', isboss = true },
        },
    },
    bmf = {
        label = 'BMF',
        grades = {
            { name = 'Young Gunners' },
            { name = 'Street Captains' },
            { name = 'Hustler' },
            { name = 'Bras Droit', isboss = true },
            { name = 'Big', isboss = true },
        },
    },
    mob = {
        label = 'MOB',
        grades = {
            { name = 'Young Boy' },
            { name = 'Boy' },
            { name = 'Youg Gangster' },
            { name = 'Gangster' },
            { name = 'Head', isboss = true },
            { name = 'Big Head', isboss = true },
        },
    },
    lco = {
        label = 'LCO',
        grades = {
            { name = 'Recrue' },
            { name = 'Membre', isboss = true },
        },
    },
    crips = {
        label = 'Crips',
        grades = {
            { name = 'Rookie Crips' },
            { name = 'Young Crips' },
            { name = 'Leader Crips' },
            { name = 'Thug Crips' },
            { name = 'Crips', isboss = true },
            { name = 'OG Crips', isboss = true },
            { name = 'King Crips', isboss = true },
        },
    },
    silentdeath = {
        label = 'Silent Death',
        grades = {
            { name = 'Umbra' },
            { name = 'Phantasma' },
            { name = 'Spiritus', isboss = true },
        },
    },
    syndicat = {
        label = 'Le Syndicat',
        grades = {
            { name = 'Executant' },
            { name = 'Soldat' },
            { name = 'Homme de Main' },
            { name = 'Assassin' },
            { name = 'Capo', isboss = true },
            { name = 'Bras droit', isboss = true },
            { name = 'Boss', isboss = true },
        },
    },
    rosanegra = {
        label = 'Cartel de la Rosa Negra',
        grades = {
            { name = 'Sicario' },
            { name = 'Soldado' },
            { name = 'Teniente', isboss = true },
            { name = 'Lideres', isboss = true },
            { name = 'Brazo Derecho', isboss = true },
            { name = 'Jefe', isboss = true },
        },
    },
    crusaders = {
        label = 'Crusaders MC',
        grades = {
            { name = 'Membre' },
            { name = 'Le Prêtre' },
            { name = 'Road Captain' },
            { name = 'Trésorier', isboss = true },
            { name = 'Secrétaire', isboss = true },
            { name = 'Sergent d\'Armes', isboss = true },
            { name = 'Vice-Président', isboss = true },
            { name = 'Président', isboss = true },
        },
    },
    punishers = {
        label = 'Punishers MC',
        grades = {
            { name = 'Prospect' },
            { name = 'Full Patch' },
            { name = 'Tailgunner' },
            { name = 'Capitaine de Route' },
            { name = 'Secrétaire', isboss = true },
            { name = 'Trésorier', isboss = true },
            { name = 'Sergent d\'Armes', isboss = true },
            { name = 'Vice-Président', isboss = true },
            { name = 'Président', isboss = true },
        },
    },
    brokers = {
        label = 'Brokers',
        grades = {
            { name = 'Lil Young' },
            { name = 'Big Young' },
            { name = 'Gangsta' },
            { name = 'Hustler', isboss = true },
            { name = 'Bras Droit', isboss = true },
            { name = 'Boss', isboss = true },
        },
    },
    ndrangheta = {
        label = 'Ndrangheta',
        grades = {
            { name = 'Recrue' },
            { name = 'Soldat' },
            { name = 'Homme de main' },
            { name = 'Lead OP', isboss = true },
            { name = 'Second', isboss = true },
            { name = 'Marraine', isboss = true },
            { name = 'Parrain', isboss = true },
        },
    },
    bloodjys = {
        label = 'Bloodjys',
        grades = {
            { name = 'Habitant' },
            { name = 'Soldat' },
            { name = 'Lieutenant', isboss = true },
            { name = 'Chef de guerre', isboss = true },
            { name = 'Commandant', isboss = true },
        },
    },
    santarosario = {
        label = 'Santa Rosario',
        grades = {
            { name = 'Soldat' },
            { name = 'Caporal' },
            { name = 'Capitaine', isboss = true },
            { name = 'Bras Gauche', isboss = true },
            { name = 'Bras Droit', isboss = true },
            { name = 'Jefe', isboss = true },
        },
    },
    jagerfly = {
        label = 'Jagerfly MC',
        grades = {
            { name = 'Support' },
            { name = 'Prospect' },
            { name = 'Full Patch' },
            { name = 'Ass kicker' },
            { name = 'Tail gunner' },
            { name = 'Enforcer' },
            { name = 'Road Captain' },
            { name = 'Secrétaire', isboss = true },
            { name = 'Trésorier', isboss = true },
            { name = 'Sergent d\'Armes', isboss = true },
            { name = 'Vice-Président', isboss = true },
            { name = 'Président', isboss = true },
        },
    },
    bws = {
        label = 'BWS',
        grades = {
            { name = 'Recrue' },
            { name = 'Homme de Main' },
            { name = 'Soldat' },
            { name = 'Lieutenant', isboss = true },
            { name = 'Second', isboss = true },
            { name = 'Boss', isboss = true },
        },
    },
    ]]
    nightkidz = {
        label = 'Night Kidz',
        grades = {
            { name = 'Recrue' },
            { name = 'Membre' },
            { name = 'Second', isboss = true },
            { name = 'Chef', isboss = true },
        },
    },
    kcorp = {
        label = 'Kcorp',
        grades = {
            { name = 'Membre', isboss = true },
        },
    },
    scavengers = {
        label = 'Scavengers',
        grades = {
            { name = 'Miteux' },
            { name = 'Charognard' },
            { name = 'Punk à Chien', isboss = true },
            { name = 'Le Roi des égouts', isboss = true },
        },
    },
    mogila = {
        label = 'Mogila',
        grades = {
            { name = 'Varbama' },
            { name = 'Ani' },
            { name = 'Gunna Grain' },
            { name = 'Tenente' },
            { name = 'King Guard' },
            { name = 'Warchief', isboss = true },
            { name = 'Koroleva', isboss = true },
            { name = 'Korot', isboss = true },
        },
    },
    duggan = {
        label = 'Duggan',
        grades = {
            { name = 'Associé' },
            { name = 'Comptable' },
            { name = 'Leader', isboss = true },
            { name = 'Bras droit', isboss = true },
            { name = 'Chief', isboss = true },
        },
    },
    lameute = {
        label = 'La Meute',
        grades = {
            { name = 'Membre' },
            { name = 'Bras Droit', isboss = true },
            { name = 'Chef', isboss = true },
        },
    },
    tij = {
        label = 'La TIJ',
        grades = {
            { name = 'Membre' },
            { name = 'Co-Boss', isboss = true },
            { name = 'Boss', isboss = true },
        },
    },
    one9ers = {
        label = 'ONE 9\'ERS',
        grades = {
            { name = 'Petit' },
            { name = 'Grand' },
            { name = 'Bras Droit', isboss = true },
            { name = 'OG', isboss = true },
        },
    },
    reyes = {
        label = 'Famille Reyes',
        grades = {
            { name = 'Nuevo' },
            { name = 'Soldado' },
            { name = 'Combatiente', isboss = true },
            { name = 'Teniente', isboss = true },
            { name = 'Tesorero', isboss = true },
            { name = 'Segundo', isboss = true },
            { name = 'Jefe', isboss = true },
        },
    },
    peoplenation = {
        label = 'People Nation',
        grades = {
            { name = 'Gangsta' },
            { name = 'OG' },
            { name = 'Double OG', isboss = true },
            { name = 'Triple OG', isboss = true },
        },
    }, 
    segadores = {
        label = 'Segadores MC',
        grades = {
            { name = 'Prospect' },
            { name = 'Miembro' },
            { name = 'Tresorero', isboss = true },
            { name = 'El secretaro', isboss = true },
            { name = 'El Pacificator', isboss = true },
            { name = 'Captain del Camino', isboss = true },
            { name = 'VP', isboss = true },
            { name = 'Presidente', isboss = true },
        },
    },
    vagos = {
        label = 'Vagos',
        grades = {
            { name = 'Habitant' },
            { name = 'Pequeno' },
            { name = 'Vagos' },
            { name = 'Teniente' },
            { name = 'Comandante' },
            { name = 'Tresorero', isboss = true },
            { name = 'Secretario' },
            { name = 'Sergento' },
            { name = 'Consultor' },
            { name = 'Segundo', isboss = true },
            { name = 'Jefe', isboss = true },
        },
    },
    phoenixorder = {
        label = 'Phoenix Order MC',
        grades = {
            { name = 'Prospect' },
            { name = 'Loyal' },
            { name = 'Enforcer' },
            { name = 'Ass kicker' },
            { name = 'Tail gunner' },
            { name = 'Road Captain' },
            { name = 'Trésorier', isboss = true },
            { name = 'Secrétaire', isboss = true },
            { name = 'Sergent d\'Armes', isboss = true },
            { name = 'Vice-Président', isboss = true },
            { name = 'Président', isboss = true },
        },
    },
    valhalla = {
        label = 'Valhalla MC',
        grades = {
            { name = 'Prospect' },
            { name = 'Membre' },
            { name = 'Capitaine de Route' },
            { name = 'Trésorier', isboss = true },
            { name = 'Sergent d\'Armes', isboss = true },
            { name = 'Vice-Président', isboss = true },
            { name = 'Président', isboss = true },
        },
    },
    ballas = {
        label = 'Ballas',
        grades = {
            { name = 'Planner' },
            { name = 'Fighter' },
            { name = 'Driver' },
            { name = 'Eclaireurs' },
            { name = 'Snitchers' },
            { name = 'Banker' },
            { name = 'Tanlent scouts' },
            { name = 'Scouts' },
            { name = 'Homies' },
            { name = 'Big Homies' },
            { name = 'Young Gangsta' },
            { name = 'Gangsta', isboss = true },
            { name = 'Hustler', isboss = true },
            { name = 'OG', isboss = true },
            { name = 'Double OG', isboss = true },
            { name = 'Triple OG', isboss = true },
        },
    },
    hustler17th = {
        label = '17th Hustler',
        grades = {
            { name = 'Little G' },
            { name = 'Gansta' },
            { name = 'Hustler' },
            { name = 'Big Hustler', isboss = true },
            { name = 'Young G', isboss = true },
            { name = 'OG', isboss = true },
        },
    },
    unypink = {
        label = 'Uny Pink',
        grades = {
            { name = 'Lil Homies' },
            { name = 'Homies' },
            { name = 'True Homies' },
            { name = 'Murda' },
            { name = 'Big Hustler' },
            { name = 'YG' },
            { name = 'Double OG', isboss = true },
            { name = 'OG', isboss = true },
        },
    },
    gitans = {
        label = 'Gitans',
        grades = {
            { name = 'La Nièce' },
            { name = 'Les Jus de Bite' },
            { name = 'Les Grands', isboss = true },
            { name = "L'Ancien", isboss = true },
        },
    },
    bcb = {
        label = 'BCB',
        grades = {
            { name = 'Esbirro' },
            { name = 'Soldado' },
            { name = 'Sergento' },
            { name = 'Teniente', isboss = true },
            { name = 'Socio', isboss = true },
            { name = 'Lider', isboss = true },
        },
    },
    theorder = {
        label = 'The Order',
        grades = {
            { name = '1ère Classe' },
            { name = 'Caporal' },
            { name = 'Sergent' },
            { name = 'Capitaine', isboss = true },
            { name = 'Colonel', isboss = true },
            { name = 'Général', isboss = true },
        },
    },
    soa = {
        label = 'Sons Of Anarchy',
        grades = {
            { name = 'Prospect' },
            { name = 'Full Patch' },
            { name = 'Enforcer' },
            { name = 'Sergent d\'Armes' },
            { name = 'Road Captain' },
            { name = 'Old Lady', isboss = true },
            { name = 'Vice-Président', isboss = true },
            { name = 'Président', isboss = true },
        },
    },
    mayans = {
        label = 'Mayans MC',
        grades = {
            { name = 'Prospect' },
            { name = 'Membre' },
            { name = 'Vétéran' },
            { name = 'Secrétaire' },
            { name = 'Sergent d\'Armes' },
            { name = 'Capitaine de Route' },
            { name = 'Trésorier', isboss = true },
            { name = 'Conseiller', isboss = true },
            { name = 'Vice-Président', isboss = true },
            { name = 'Président', isboss = true },
        },
    },
    babydriver = {
        label = 'Baby Driver',
        grades = {
            { name = 'Recrue' },
            { name = 'Driver Confirmé' },
            { name = 'Pilote' },
            { name = 'Wheelman', isboss = true },
        },
    },
}
