QBShared = QBShared or {}
QBShared.Gangs = {
    civil = { label = 'Civil', grades = { { name = 'Sans Affiliation' } } },
    miamiboyz = {
        label = 'Miami Boyz',
        grades = {
            { name = 'Habitant' },
            { name = 'Homies' },
            { name = 'Gangsta' },
            { name = 'Hustler' },
            { name = 'Big Hustler' },
            { name = 'Triple OG', isboss = true },
            { name = 'Double OG', isboss = true },
            { name = 'OG', isboss = true },
        },
    },
    braithemb = {
        label = 'Braithem B',
        grades = {
            { name = 'Private E-1' },
            { name = 'Private E-2' },
            { name = 'Caporal' },
            { name = 'Sergent' },
            { name = '1er Lieutenant' },
            { name = 'Capitaine', isboss = true },
            { name = 'Major', isboss = true },
        },
    },
    losvalentinos = {
        label = 'Los Valentinos',
        grades = {
            { name = 'Parasite' },
            { name = 'Postulant' },
            { name = 'Membre Honoraire' },
            { name = 'Membre Attitré' },
            { name = '1ère Classe' },
            { name = 'Caporal' },
            { name = 'Sergent d\'Armes' },
            { name = 'Trésorier' },
            { name = 'Secrétaire', isboss = true },
            { name = 'Vice-Président', isboss = true },
            { name = 'Président', isboss = true },
        },
    },
    piru = {
        label = 'Piru Streetboys',
        grades = {
            { name = 'Petit' },
            { name = 'Moyen' },
            { name = 'Grand' },
            { name = 'Bras Droit', isboss = true },
            { name = 'OG', isboss = true },
        },
    },
    nemesis = {
        label = 'Némésis',
        grades = {
            { name = 'Aspirant' },
            { name = 'Associé' },
            { name = 'Second', isboss = true },
            { name = 'Conseiller', isboss = true },
            { name = 'Padre', isboss = true },
        },
    },
    fuerzaespinoza = {
        label = 'Fuerza Espinoza',
        grades = {
            { name = 'Teniente' },
            { name = 'Segundo' },
            { name = 'Commandante', isboss = true },
            { name = 'Jefe', isboss = true },
        },
    },
    endofwatch = {
        label = 'End Of Watch',
        grades = {
            { name = 'Recrue' },
            { name = 'Homme de Main' },
            { name = 'Représentant' },
            { name = 'Lieutenant', isboss = true },
            { name = 'Capitaine', isboss = true },
            { name = 'Leader', isboss = true },
        },
    },
    lapiovra = {
        label = 'La Piovra',
        grades = {
            { name = 'Tentacule Visible' },
            { name = 'Tentacule Invisible' },
            { name = 'Leader', isboss = true },
        },
    },
    triade = {
        label = 'Triade Xin Yi An',
        grades = {
            { name = 'Membre' },
            { name = 'Officier d\'Execution' },
            { name = 'Officier Général' },
            { name = 'Officier d\'Administration' },
            { name = 'Officier des Liaisons' },
            { name = 'Maitre des Opérations' },
            { name = 'Maitre des Cérémonies' },
            { name = 'Seconde Tête', isboss = true },
            { name = 'Tête de Dragon', isboss = true },
        },
    },
    bmf = {
        label = 'BMF',
        grades = {
            { name = 'Recrue' },
            { name = 'Homme de Main' },
            { name = 'Gangster' },
            { name = 'Lieutenant' },
            { name = 'Second', isboss = true },
            { name = 'Boss', isboss = true },
        },
    },
    soa = {
        label = 'Sons Of Anarchy',
        grades = {
            { name = 'Nomades' },
            { name = 'Propspect' },
            { name = 'Tail Gunner' },
            { name = 'Ass Kicker' },
            { name = 'Enforcer' },
            { name = 'Treasurer' },
            { name = 'Road Captain' },
            { name = 'Secretary' },
            { name = 'Sgt At Arms' },
            { name = 'Vice-Président', isboss = true },
            { name = 'Président', isboss = true },
        },
    },
    cosanostra = {
        label = 'Cosa Nostra',
        grades = {
            { name = 'Soldat' },
            { name = 'Caporal' },
            { name = 'Sergent' },
            { name = 'Major' },
            { name = 'Bras Droit', isboss = true },
            { name = 'Don', isboss = true },
        },
    },
    vagos = {
        label = 'Vagos',
        grades = {
            { name = 'Pequeno' },
            { name = 'Soldado' },
            { name = 'Commandante' },
            { name = 'Teniente' },
            { name = 'Segundo', isboss = true },
            { name = 'Jefe', isboss = true },
        },
    },
    mob = {
        label = 'MOB',
        grades = {
            { name = 'Young Boy' },
            { name = 'Boy' },
            { name = 'Youg Gangster' },
            { name = 'Gangster' },
            { name = 'Head', isboss = true },
            { name = 'Big Head', isboss = true },
        },
    },
    ms13 = {
        label = 'MS13',
        grades = {
            { name = 'Pequeno' },
            { name = 'Soldado' },
            { name = 'Grande' },
            { name = 'Sergendo' },
            { name = 'Mano Derecha', isboss = true },
            { name = 'Jefe/a', isboss = true },
        },
    },
    lco = {
        label = 'LCO',
        grades = {
            { name = 'Recrue' },
            { name = 'Membre', isboss = true },
        },
    },
    hargreeves = {
        label = 'Famille Hargreeves',
        grades = {
            { name = 'Membre', isboss = true },
        },
    },
    nightkidz = {
        label = 'Night Kidz',
        grades = {
            { name = 'Recrue' },
            { name = 'Membre' },
            { name = 'Second', isboss = true },
            { name = 'Chef', isboss = true },
        },
    },
    kcorp = {
        label = 'Kcorp',
        grades = {
            { name = 'Membre', isboss = true },
        },
    },
    crips = {
        label = 'Crips',
        grades = {
            { name = 'Homies' },
            { name = 'Gangsta' },
            { name = 'R.G' },
            { name = 'Y.G' },
            { name = 'O.G', isboss = true },
        },
    },
    latinscorpion = {
        label = 'Latin Scorpion',
        grades = {
            { name = 'Habitante' },
            { name = 'Pequeno' },
            { name = 'Grande', isboss = true },
        },
    },
    cjng = {
        label = 'Cartel Jalisco Nouvelle Generation',
        grades = {
            { name = 'Narcomenuedistas' },
            { name = 'Miembro de Plaza' },
            { name = 'Sicario' },
            { name = 'Teniente' },
            { name = 'Jefes de Sicarios' },
            { name = 'Lideres de Plaza', isboss = true },
            { name = 'Capo Los Santos Country', isboss = true },
            { name = 'Capo Blaine County', isboss = true },
            { name = 'Comandantes', isboss = true },
            { name = 'Jefe del Territorio', isboss = true },
        },
    },
    ttk = {
        label = 'Train To Kill',
        grades = {
            { name = 'Lil\' Guy' },
            { name = 'Gangster' },
            { name = 'Hustler' },
            { name = 'OG', isboss = true },
            { name = 'Underboss', isboss = true },
            { name = 'Boss', isboss = true },
        },
    },
    dsr = {
        label = 'Dark Street Runners',
        grades = {
            { name = 'Urban Novice' },
            { name = 'Lunar Navigateur' },
            { name = 'Dark Mechanic' },
            { name = 'Eclipse Enforcer' },
            { name = 'Phantom Driver' },
            { name = 'Shadow Strategist' },
            { name = 'Night Co-Leader', isboss = true },
            { name = 'Night Leader', isboss = true },
        },
    },
    reapers = {
        label = 'Reapers',
        grades = {
            { name = 'Recrue' },
            { name = 'Homme de Main' },
            { name = 'Lieutenant' },
            { name = 'Conseiller' },
            { name = 'Caporal', isboss = true },
            { name = 'Second', isboss = true },
            { name = 'Boss', isboss = true },
        },
    },
    scavengers = {
        label = 'Scavengers',
        grades = {
            { name = 'Miteux' },
            { name = 'Charognard' },
            { name = 'Punk à Chien', isboss = true },
            { name = 'Le Roi des égouts', isboss = true },
        },
    },
    malvabundos = {
        label = 'Malvabundos',
        grades = {
            { name = 'Prospect' },
            { name = 'Membre' },
            { name = 'Road Captain' },
            { name = 'Trésorier' },
            { name = 'Secrétaire' },
            { name = 'Sgt At Arms' },
            { name = 'Vice-Président', isboss = true },
            { name = 'Président', isboss = true },
        },
    },
    gitans = {
        label = 'Gitans',
        grades = {
            { name = 'Cousins' },
            { name = 'Sous-Patriarche', isboss = true },
            { name = 'Patriarche', isboss = true },
        },
    },
    greenhustler = {
        label = 'Green Hustler',
        grades = {
            { name = 'Little G' },
            { name = 'Gangsta' },
            { name = 'Hustler' },
            { name = 'Big Hustler' },
            { name = 'Young-G', isboss = true },
            { name = 'OG', isboss = true },
        },
    },
    verdugos = {
        label = 'Verdugos MC',
        grades = {
            { name = 'Support' },
            { name = 'Prospect' },
            { name = 'Tailgunner' },
            { name = 'Enforcer' },
            { name = 'Full Patch' },
            { name = 'Road Captain' },
            { name = 'Sergent d\'Armes' },
            { name = 'Trésorier' },
            { name = 'Vice-Président', isboss = true },
            { name = 'Président', isboss = true },
        },
    },
    silentdeath = {
        label = 'Silent Death',
        grades = {
            { name = 'Umbra' },
            { name = 'Phantasma' },
            { name = 'Spiritus', isboss = true },
        },
    },
    ubc = {
        label = 'UBC',
        grades = {
            { name = 'Petit Nouveau' },
            { name = 'Membre Confirmé' },
            { name = 'Second', isboss = true },
            { name = 'Chef', isboss = true },
        },
    },
    lost = {
        label = 'The LOST MC',
        grades = {
            { name = 'Prospect' },
            { name = 'Membre' },
            { name = 'Représentant' },
            { name = 'Trésorier' },
            { name = 'Secrétaire' },
            { name = 'Sergent At Arms' },
            { name = 'Vice-Président', isboss = true },
            { name = 'Président', isboss = true },
        },
    },
    mogila = {
        label = 'Mogila',
        grades = {
            { name = 'Varbama' },
            { name = 'Ani' },
            { name = 'Gunna Grain' },
            { name = 'Tenente' },
            { name = 'King Guard' },
            { name = 'Warchief', isboss = true },
            { name = 'Koroleva', isboss = true },
            { name = 'Korot', isboss = true },
        },
    },
    comptonwest = {
        label = 'Compton West',
        grades = {
            { name = 'Habitant' },
            { name = 'Rookie' },
            { name = 'Young Gangsta' },
            { name = 'Leader' },
            { name = 'Original Gangsta' },
            { name = 'Real Gangsta', isboss = true },
            { name = 'Old Gangsta', isboss = true },
            { name = 'Gangsta King', isboss = true },
        },
    },
    lossalvador = {
        label = 'Los Salvador',
        grades = {
            { name = 'Executant' },
            { name = 'Soldat' },
            { name = 'Chef de Régime' },
            { name = 'Bras Droit', isboss = true },
            { name = 'Consiglio', isboss = true },
            { name = 'Parrain', isboss = true },
        },
    },
    comando = {
        label = 'Comando Vermelho',
        grades = {
            { name = 'Novinho' },
            { name = 'Soldado' },
            { name = 'Favelado' },
            { name = 'Chef de Divisao' },
            { name = 'Terro' },
            { name = 'Chef Geral', isboss = true },
            { name = 'Braco Direito', isboss = true },
            { name = 'Chef', isboss = true },
        },
    },
    hoovers = {
        label = 'Hoovers',
        grades = {
            { name = 'Novato' },
            { name = 'La Madrina' },
            { name = 'Soldado' },
            { name = 'Peroguardian' },
            { name = 'Grande' },
            { name = 'El Teniente', isboss = true },
            { name = 'El Segundo', isboss = true },
            { name = 'El Jefe', isboss = true },
        },
    },
    blackd = {
        label = 'Black D',
        grades = {
            { name = 'Petite Frappe' },
            { name = 'Trafiquant' },
            { name = 'Grangster' },
            { name = 'Big Gangster' },
            { name = 'G Boy', isboss = true },
            { name = 'Joker', isboss = true },
            { name = 'Kipster', isboss = true },
            { name = 'Top G', isboss = true },
        },
    },
    crew = {
        label = 'Crew',
        grades = {
            { name = 'OG des OGM', isboss = true },
            { name = 'OG des Culs de Joints', isboss = true },
            { name = 'OG de la Boite à Gants', isboss = true },
            { name = 'OG des Cartons', isboss = true },
            { name = 'OG du Crack', isboss = true },
            { name = 'OG des Rats', isboss = true },
            { name = 'OG du Canapé', isboss = true },
        },
    },
}
