QBShared = QBShared or {}
QBShared.Weapons = {
	-- // WEAPONS
	-- Melee
	[`weapon_unarmed`] 				 = {['name'] = 'weapon_unarmed', 		['label'] = 'Poings', 				['emsreason'] = 'Poings', ['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'Tué en Mêlée / Frappé / Exécuté'},
	[`weapon_dagger`] 				 = {['name'] = 'weapon_dagger', 		['label'] = 'Dague', 				['emsreason'] = 'Objet Tranchant', ['weapontype'] = 'Melee',	['ammotype'] = nil,	['damagereason'] = 'Knifed / Poignardé / Etripé'},
	[`weapon_bat`] 					 = {['name'] = 'weapon_bat', 			['label'] = 'Batte', 					['emsreason'] = 'Objet Contondant', ['weapontype'] = 'Melee',	['ammotype'] = nil,	['damagereason'] = 'Tué en Mêlée / Frappé / Exécuté'},
	[`weapon_bottle`] 				 = {['name'] = 'weapon_bottle', 		['label'] = 'Bouteille Cassée', 		['emsreason'] = 'Objet Tranchant', ['weapontype'] = 'Melee',	['ammotype'] = nil,	['damagereason'] = 'Knifed / Poignardé / Etripé'},
	[`weapon_crowbar`] 				 = {['name'] = 'weapon_crowbar', 		['label'] = 'Pied de Biche', 				['emsreason'] = 'Objet Contondant', ['weapontype'] = 'Melee',	['ammotype'] = nil,	['damagereason'] = 'Tué en Mêlée / Frappé / Exécuté'},
	[`weapon_flashlight`] 			 = {['name'] = 'weapon_flashlight', 	['label'] = 'Lampe Torche', 			['emsreason'] = 'Objet Contondant', ['weapontype'] = 'Melee',	['ammotype'] = nil,	['damagereason'] = 'Tué en Mêlée / Frappé / Exécuté'},
	[`weapon_golfclub`] 			 = {['name'] = 'weapon_golfclub', 		['label'] = 'Club de Golf', 			['emsreason'] = 'Objet Contondant', ['weapontype'] = 'Melee',	['ammotype'] = nil,	['damagereason'] = 'Tué en Mêlée / Frappé / Exécuté'},
	[`weapon_hammer`] 				 = {['name'] = 'weapon_hammer', 		['label'] = 'Marteau', 				['emsreason'] = 'Objet Contondant', ['weapontype'] = 'Melee',	['ammotype'] = nil,	['damagereason'] = 'Tué en Mêlée / Frappé / Exécuté'},
	[`weapon_hatchet`] 				 = {['name'] = 'weapon_hatchet', 		['label'] = 'Hachette', 				['emsreason'] = 'Objet Tranchant', ['weapontype'] = 'Melee',	['ammotype'] = nil,	['damagereason'] = 'Knifed / Poignardé / Etripé'},
	[`weapon_knuckle`] 				 = {['name'] = 'weapon_knuckle', 		['label'] = 'Poing Américain', 				['emsreason'] = 'Objet Contondant', ['weapontype'] = 'Melee',	['ammotype'] = nil,	['damagereason'] = 'Tué en Mêlée / Frappé / Exécuté'},
	[`weapon_knife`] 				 = {['name'] = 'weapon_knife', 			['label'] = 'Couteau', 				['emsreason'] = 'Objet Tranchant', ['weapontype'] = 'Melee',	['ammotype'] = nil,	['damagereason'] = 'Knifed / Poignardé / Etripé'},
	[`weapon_machete`] 				 = {['name'] = 'weapon_machete', 		['label'] = 'Machette', 				['emsreason'] = 'Objet Tranchant', ['weapontype'] = 'Melee',	['ammotype'] = nil,	['damagereason'] = 'Knifed / Poignardé / Etripé'},
	[`weapon_switchblade`] 			 = {['name'] = 'weapon_switchblade', 	['label'] = 'Couteau à Cran d\'Arrêt', 			['emsreason'] = 'Objet Tranchant', ['weapontype'] = 'Melee',	['ammotype'] = nil,	['damagereason'] = 'Knifed / Poignardé / Etripé'},
	[`weapon_nightstick`] 			 = {['name'] = 'weapon_nightstick', 	['label'] = 'Matraque', 			['emsreason'] = 'Objet Contondant', ['weapontype'] = 'Melee',	['ammotype'] = nil,	['damagereason'] = 'Tué en Mêlée / Frappé / Exécuté'},
	[`weapon_wrench`] 				 = {['name'] = 'weapon_wrench', 		['label'] = 'Clé à Pipe', 				['emsreason'] = 'Objet Contondant', ['weapontype'] = 'Melee',	['ammotype'] = nil,	['damagereason'] = 'Tué en Mêlée / Frappé / Exécuté'},
	[`weapon_battleaxe`] 			 = {['name'] = 'weapon_battleaxe', 		['label'] = 'Hache de Combat', 			['emsreason'] = 'Objet Tranchant', ['weapontype'] = 'Melee',	['ammotype'] = nil,	['damagereason'] = 'Knifed / Poignardé / Etripé'},
	[`weapon_poolcue`] 				 = {['name'] = 'weapon_poolcue', 		['label'] = 'Queue de Billard', 				['emsreason'] = 'Objet Contondant', ['weapontype'] = 'Melee',	['ammotype'] = nil,	['damagereason'] = 'Tué en Mêlée / Frappé / Exécuté'},
	[`weapon_briefcase`] 			 = {['name'] = 'weapon_briefcase', 		['label'] = 'Mallette', 			['emsreason'] = 'Objet Contondant', ['weapontype'] = 'Melee',	['ammotype'] = nil,	['damagereason'] = 'Tué en Mêlée / Frappé / Exécuté'},
	[`weapon_briefcase_02`] 		 = {['name'] = 'weapon_briefcase_02', 	['label'] = 'Mallette', 			['emsreason'] = 'Objet Contondant', ['weapontype'] = 'Melee',	['ammotype'] = nil,	['damagereason'] = 'Tué en Mêlée / Frappé / Exécuté'},
	[`weapon_garbagebag`] 			 = {['name'] = 'weapon_garbagebag', 	['label'] = 'Sac Poubelle', 			['emsreason'] = 'Objet Contondant', ['weapontype'] = 'Melee',	['ammotype'] = nil,	['damagereason'] = 'Tué en Mêlée / Frappé / Exécuté'},
	[`weapon_handcuffs`] 			 = {['name'] = 'weapon_handcuffs', 		['label'] = 'Menottes', 			['emsreason'] = 'Objet Contondant', ['weapontype'] = 'Melee',	['ammotype'] = nil,	['damagereason'] = 'Tué en Mêlée / Frappé / Exécuté'},
	[`weapon_bread`] 				 = {['name'] = 'weapon_bread', 			['label'] = 'Baguette', 			['emsreason'] = 'Objet Contondant', ['weapontype'] = 'Melee',	['ammotype'] = nil,	['damagereason'] = 'Tué en Mêlée / Frappé / Exécuté'},
	[`weapon_stone_hatchet`] 		 = {['name'] = 'weapon_stone_hatchet', 	['label'] = 'Hachette en Pierre',        ['emsreason'] = 'Objet Tranchant', ['weapontype'] = 'Melee',	['ammotype'] = nil,	['damagereason'] = 'Knifed / Poignardé / Etripé'},
	[`weapon_candycane`]			 = {['name'] = 'weapon_candycane',		['label'] = 'Sucre d\'Orge',			['emsreason'] = 'Objet Contondant', ['weapontype'] = 'Melee',	['ammotype'] = nil,	['damagereason'] = 'Tué en Mêlée / Frappé / Exécuté'},

    -- Handguns
	[`weapon_pistol`] 				 = {['name'] = 'weapon_pistol', 		['label'] = 'Pistolet', 				    ['emsreason'] = 'Arme Petit Calibre', ['weapontype'] = 'Pistol',	['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Abattu par un pistolet'},
	[`weapon_pistol_mk2`] 			 = {['name'] = 'weapon_pistol_mk2', 	['label'] = 'Pistolet Mk2', 			    ['emsreason'] = 'Arme Petit Calibre', ['weapontype'] = 'Pistol',	['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Abattu par un pistolet'},
	[`weapon_combatpistol`] 		 = {['name'] = 'weapon_combatpistol', 	['label'] = 'Pistolet de Combat', 			['emsreason'] = 'Arme Petit Calibre', ['weapontype'] = 'Pistol',	['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Abattu par un pistolet'},
	[`weapon_appistol`] 			 = {['name'] = 'weapon_appistol', 		['label'] = 'Pistolet Automatique', 				['emsreason'] = 'Arme Petit Calibre', ['weapontype'] = 'Pistol',	['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Abattu par un pistolet'},
	[`weapon_stungun`] 				 = {['name'] = 'weapon_stungun', 		['label'] = 'Taser', 					['emsreason'] = 'Taser', ['weapontype'] = 'Pistol',	['ammotype'] = 'AMMO_STUNGUN',	['damagereason'] = 'Mort'},
	[`weapon_pistol50`] 			 = {['name'] = 'weapon_pistol50', 		['label'] = 'Pistolet Cal .50 ', 			['emsreason'] = 'Arme Petit Calibre', ['weapontype'] = 'Pistol',	['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Abattu par un pistolet'},
	[`weapon_snspistol`] 			 = {['name'] = 'weapon_snspistol', 		['label'] = 'Pistolet SNS', 				['emsreason'] = 'Arme Petit Calibre', ['weapontype'] = 'Pistol',	['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Abattu par un pistolet'},
	[`weapon_snspistol_mk2`] 	     = {['name'] = 'weapon_snspistol_mk2', 	['label'] = 'Pistolet SNS MK2', 			['emsreason'] = 'Arme Petit Calibre', ['weapontype'] = 'Pistol',	['ammotype'] = 'AMMO_PISTOL',   ['damagereason'] = 'Abattu par un pistolet'},
	[`weapon_heavypistol`] 			 = {['name'] = 'weapon_heavypistol', 	['label'] = 'Pistolet Lourd', 			['emsreason'] = 'Arme Petit Calibre', ['weapontype'] = 'Pistol',	['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Abattu par un pistolet'},
	[`weapon_vintagepistol`] 		 = {['name'] = 'weapon_vintagepistol', 	['label'] = 'Pistolet Vintage', 			['emsreason'] = 'Arme Petit Calibre', ['weapontype'] = 'Pistol',	['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Abattu par un pistolet'},
	[`weapon_flaregun`] 			 = {['name'] = 'weapon_flaregun', 		['label'] = 'Pistolet de Détresse', 				['emsreason'] = 'Brûlure', ['weapontype'] = 'Pistol',	['ammotype'] = 'AMMO_FLARE',	['damagereason'] = 'Mort'},
	[`weapon_marksmanpistol`] 		 = {['name'] = 'weapon_marksmanpistol', ['label'] = 'Pistolet Marksman', 			['emsreason'] = 'Arme Petit Calibre', ['weapontype'] = 'Pistol',	['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Abattu par un pistolet'},
	[`weapon_revolver`] 			 = {['name'] = 'weapon_revolver', 		['label'] = 'Revolver', 				['emsreason'] = 'Arme Petit Calibre', ['weapontype'] = 'Pistol',	['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Abattu par un pistolet'},
	[`weapon_revolver_mk2`] 		 = {['name'] = 'weapon_revolver_mk2', 	['label'] = 'Revolver MK2', 		    ['emsreason'] = 'Arme Petit Calibre', ['weapontype'] = 'Pistol',	['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Abattu par un pistolet'},
	[`weapon_doubleaction`] 	     = {['name'] = 'weapon_doubleaction', 	['label'] = 'Revolver Double Action',	['emsreason'] = 'Arme Petit Calibre', ['weapontype'] = 'Pistol',	['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Abattu par un pistolet'},
	[`weapon_raypistol`]			 = {['name'] = 'weapon_raypistol',		['label'] = 'Pistolet Laser',			    ['emsreason'] = 'Brûlure', ['weapontype'] = 'Pistol',	['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Abattu par un pistolet'},
	[`weapon_ceramicpistol`]		 = {['name'] = 'weapon_ceramicpistol', 	['label'] = 'Pistolet Céramique',		    ['emsreason'] = 'Arme Petit Calibre', ['weapontype'] = 'Pistol',	['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Abattu par un pistolet'},
	[`weapon_navyrevolver`]        	 = {['name'] = 'weapon_navyrevolver', 	['label'] = 'Revolver Navy',		    ['emsreason'] = 'Arme Petit Calibre', ['weapontype'] = 'Pistol',	['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Abattu par un pistolet'},
	[`weapon_gadgetpistol`] 		 = {['name'] = 'weapon_gadgetpistol', 	['label'] = 'Pistolet Gadget',		    ['emsreason'] = 'Arme Petit Calibre', ['weapontype'] = 'Pistol',	['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Abattu par un pistolet'},
	[`weapon_stungun_mp`] 			 = {['name'] = 'weapon_stungun_mp', 	['label'] = 'Taser', 					['emsreason'] = 'Taser', ['weapontype'] = 'Pistol',	['ammotype'] = 'AMMO_STUNGUN',	['damagereason'] = 'Mort'},
	[`weapon_pistolxm3`]			 = {['name'] = 'weapon_pistolxm3',		['label'] = 'Pistolet XM3',				['emsreason'] = 'Arme Petit Calibre', ['weapontype'] = 'Pistol',	['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plaugged / Bust a cap in'},

    -- Submachine Guns
	[`weapon_microsmg`] 			 = {['name'] = 'weapon_microsmg', 		['label'] = 'UZI', 			['emsreason'] = 'Arme Petit Calibre', ['weapontype'] = 'Submachine Gun',	['ammotype'] = 'AMMO_SMG',		['damagereason'] = 'Abattu par une mitraillette'},
	[`weapon_smg`] 				 	 = {['name'] = 'weapon_smg', 			['label'] = 'MP5', 					['emsreason'] = 'Arme Petit Calibre', ['weapontype'] = 'Submachine Gun',	['ammotype'] = 'AMMO_SMG',		['damagereason'] = 'Abattu par une mitraillette'},
	[`weapon_smg_mk2`] 				 = {['name'] = 'weapon_smg_mk2', 		['label'] = 'MP5 MK2', 			    ['emsreason'] = 'Arme Petit Calibre', ['weapontype'] = 'Submachine Gun',	['ammotype'] = 'AMMO_SMG',		['damagereason'] = 'Abattu par une mitraillette'},
	[`weapon_assaultsmg`] 			 = {['name'] = 'weapon_assaultsmg', 	['label'] = 'P90', 			['emsreason'] = 'Arme Petit Calibre', ['weapontype'] = 'Submachine Gun',	['ammotype'] = 'AMMO_SMG',		['damagereason'] = 'Abattu par une mitraillette'},
	[`weapon_combatpdw`] 			 = {['name'] = 'weapon_combatpdw', 		['label'] = 'PDW', 			['emsreason'] = 'Arme Petit Calibre', ['weapontype'] = 'Submachine Gun',	['ammotype'] = 'AMMO_SMG',		['damagereason'] = 'Abattu par une mitraillette'},
	[`weapon_machinepistol`] 		 = {['name'] = 'weapon_machinepistol', 	['label'] = 'Tec-9', 				['emsreason'] = 'Arme Petit Calibre', ['weapontype'] = 'Submachine Gun',	['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Abattu par une mitraillette'},
	[`weapon_minismg`] 				 = {['name'] = 'weapon_minismg', 		['label'] = 'Scorpion', 			['emsreason'] = 'Arme Petit Calibre', ['weapontype'] = 'Submachine Gun',	['ammotype'] = 'AMMO_SMG',		['damagereason'] = 'Abattu par une mitraillette'},
	[`weapon_raycarbine`]	         = {['name'] = 'weapon_raycarbine', 	['label'] = 'Fusil Laser',	        ['emsreason'] = 'Arme Futuriste', ['weapontype'] = 'Submachine Gun',	['ammotype'] = 'AMMO_SMG',		['damagereason'] = 'Abattu par une mitraillette'},

    -- Shotguns
	[`weapon_pumpshotgun`] 			 = {['name'] = 'weapon_pumpshotgun', 	 	['label'] = 'Fusil à Pompe', 			['emsreason'] = 'Fusil à Pompe', ['weapontype'] = 'Shotgun',	['ammotype'] = 'AMMO_SHOTGUN',	['damagereason'] = 'Abattu par un fusil à pompe'},
	[`weapon_pumpshotgun_mk2`]		 = {['name'] = 'weapon_pumpshotgun_mk2',	['label'] = 'Fusil à Pompe MK2', 		['emsreason'] = 'Fusil à Pompe', ['weapontype'] = 'Shotgun',	['ammotype'] = 'AMMO_SHOTGUN',	['damagereason'] = 'Abattu par un fusil à pompe'},
	[`weapon_sawnoffshotgun`] 		 = {['name'] = 'weapon_sawnoffshotgun', 	['label'] = 'Fusil à Canon Scié', 		['emsreason'] = 'Fusil à Pompe', ['weapontype'] = 'Shotgun',	['ammotype'] = 'AMMO_SHOTGUN',	['damagereason'] = 'Abattu par un fusil à pompe'},
	[`weapon_assaultshotgun`] 		 = {['name'] = 'weapon_assaultshotgun', 	['label'] = 'Fusil à Pompe d\'Assault', 			['emsreason'] = 'Fusil à Pompe', ['weapontype'] = 'Shotgun',	['ammotype'] = 'AMMO_SHOTGUN',	['damagereason'] = 'Abattu par un fusil à pompe'},
	[`weapon_bullpupshotgun`] 		 = {['name'] = 'weapon_bullpupshotgun', 	['label'] = 'Fusil à Pompe Bullpup', 			['emsreason'] = 'Fusil à Pompe', ['weapontype'] = 'Shotgun',	['ammotype'] = 'AMMO_SHOTGUN',	['damagereason'] = 'Abattu par un fusil à pompe'},
	[`weapon_musket`] 			     = {['name'] = 'weapon_musket', 			['label'] = 'Mousquet', 					['emsreason'] = 'Mousquet', ['weapontype'] = 'Shotgun',	['ammotype'] = 'AMMO_SHOTGUN',	['damagereason'] = 'Abattu par un fusil à pompe'},
	[`weapon_heavyshotgun`] 		 = {['name'] = 'weapon_heavyshotgun', 	 	['label'] = 'Fusil à Pompe Lourd', 			['emsreason'] = 'Fusil à Pompe', ['weapontype'] = 'Shotgun',	['ammotype'] = 'AMMO_SHOTGUN',	['damagereason'] = 'Abattu par un fusil à pompe'},
	[`weapon_dbshotgun`] 			 = {['name'] = 'weapon_dbshotgun', 		 	['label'] = 'Fusil à Double Canon', 	['emsreason'] = 'Fusil à Pompe', ['weapontype'] = 'Shotgun',	['ammotype'] = 'AMMO_SHOTGUN',	['damagereason'] = 'Abattu par un fusil à pompe'},
	[`weapon_autoshotgun`] 			 = {['name'] = 'weapon_autoshotgun', 	 	['label'] = 'Fusil à Pompe Auto', 			['emsreason'] = 'Fusil à Pompe', ['weapontype'] = 'Shotgun',	['ammotype'] = 'AMMO_SHOTGUN',	['damagereason'] = 'Abattu par un fusil à pompe'},
	[`weapon_combatshotgun`]		 = {['name'] = 'weapon_combatshotgun', 		['label'] = 'Fusil à Pompe de Combat',		    ['emsreason'] = 'Fusil à Pompe', ['weapontype'] = 'Shotgun',	['ammotype'] = 'AMMO_SHOTGUN',	['damagereason'] = 'Abattu par un fusil à pompe'},

    -- Assault Rifles
	[`weapon_assaultrifle`] 		 = {['name'] = 'weapon_assaultrifle', 	 	['label'] = 'AK-47', 				['emsreason'] = 'Arme Calibre Moyen', ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Abattu par un fusil d\'assault'},
	[`weapon_assaultrifle_mk2`] 	 = {['name'] = 'weapon_assaultrifle_mk2', 	['label'] = 'AK-47 MK2', 			['emsreason'] = 'Arme Calibre Moyen', ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Abattu par un fusil d\'assault'},
	[`weapon_carbinerifle`] 		 = {['name'] = 'weapon_carbinerifle', 	 	['label'] = 'M4', 				['emsreason'] = 'Arme Calibre Moyen', ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Abattu par un fusil d\'assault'},
    [`weapon_carbinerifle_mk2`] 	 = {['name'] = 'weapon_carbinerifle_mk2', 	['label'] = 'M4 MK2', 			['emsreason'] = 'Arme Calibre Moyen', ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Abattu par un fusil d\'assault'},
	[`weapon_advancedrifle`] 		 = {['name'] = 'weapon_advancedrifle', 	 	['label'] = 'TAR 21', 				['emsreason'] = 'Arme Calibre Moyen', ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Abattu par un fusil d\'assault'},
	[`weapon_specialcarbine`] 		 = {['name'] = 'weapon_specialcarbine', 	['label'] = 'G36', 				['emsreason'] = 'Arme Calibre Moyen', ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Abattu par un fusil d\'assault'},
	[`weapon_specialcarbine_mk2`]	 = {['name'] = 'weapon_specialcarbine_mk2',	['label'] = 'G36 MK2',	        ['emsreason'] = 'Arme Calibre Moyen', ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Abattu par un fusil d\'assault'},
	[`weapon_bullpuprifle`] 		 = {['name'] = 'weapon_bullpuprifle', 	 	['label'] = 'QBZ', 				['emsreason'] = 'Arme Calibre Moyen', ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Abattu par un fusil d\'assault'},
	[`weapon_bullpuprifle_mk2`]		 = {['name'] = 'weapon_bullpuprifle_mk2', 	['label'] = 'QBZ MK2',			['emsreason'] = 'Arme Calibre Moyen', ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Abattu par un fusil d\'assault'},
	[`weapon_compactrifle`] 		 = {['name'] = 'weapon_compactrifle', 	 	['label'] = 'AK-U', 				['emsreason'] = 'Arme Calibre Moyen', ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Abattu par un fusil d\'assault'},
	[`weapon_militaryrifle`]		 = {['name'] = 'weapon_militaryrifle', 		['label'] = 'AUG',   			['emsreason'] = 'Arme Calibre Moyen', ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Abattu par un fusil d\'assault'},
    [`weapon_heavyrifle`] 			 = {['name'] = 'weapon_heavyrifle', 	 	['label'] = 'SCAR-H', 					['emsreason'] = 'Arme Calibre Moyen', ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Abattu par un fusil d\'assault'},

    -- Light Machine Guns
	[`weapon_mg`] 					 = {['name'] = 'weapon_mg', 			['label'] = 'Mitrailleuse', 			['emsreason'] = 'Arme Gros Calibre', ['weapontype'] = 'Light Machine Gun',	['ammotype'] = 'AMMO_MG',	['damagereason'] = 'Abattu par une mitrailleuse'},
	[`weapon_combatmg`] 			 = {['name'] = 'weapon_combatmg', 		['label'] = 'Mitrailleuse de Combat', 			['emsreason'] = 'Arme Gros Calibre', ['weapontype'] = 'Light Machine Gun',	['ammotype'] = 'AMMO_MG',	['damagereason'] = 'Abattu par une mitrailleuse'},
	[`weapon_combatmg_mk2`]	 		 = {['name'] = 'weapon_combatmg_mk2', 	['label'] = 'Mitrailleuse de Combat MK2',	    ['emsreason'] = 'Arme Gros Calibre', ['weapontype'] = 'Light Machine Gun',	['ammotype'] = 'AMMO_MG',	['damagereason'] = 'Abattu par une mitrailleuse'},
	[`weapon_gusenberg`] 			 = {['name'] = 'weapon_gusenberg', 		['label'] = 'Thompson', 		['emsreason'] = 'Arme Gros Calibre', ['weapontype'] = 'Light Machine Gun',	['ammotype'] = 'AMMO_MG',	['damagereason'] = 'Abattu par une mitrailleuse'},

    -- Sniper Rifles
	[`weapon_sniperrifle`] 			 = {['name'] = 'weapon_sniperrifle', 	 	['label'] = 'Fusil de Précision', 			['emsreason'] = 'Arme Gros Calibre', ['weapontype'] = 'Sniper Rifle',	['ammotype'] = 'AMMO_SNIPER',			['damagereason'] = 'Abattu par un fusil de précision'},
	[`weapon_heavysniper`] 			 = {['name'] = 'weapon_heavysniper', 	 	['label'] = 'Fusil de Précision Lourd', 			['emsreason'] = 'Arme Gros Calibre', ['weapontype'] = 'Sniper Rifle',	['ammotype'] = 'AMMO_SNIPER',			['damagereason'] = 'Abattu par un fusil de précision'},
	[`weapon_heavysniper_mk2`]		 = {['name'] = 'weapon_heavysniper_mk2', 	['label'] = 'Fusil de Précision Lourd MK2',	        ['emsreason'] = 'Arme Gros Calibre', ['weapontype'] = 'Sniper Rifle',	['ammotype'] = 'AMMO_SNIPER',			['damagereason'] = 'Abattu par un fusil de précision'},
	[`weapon_marksmanrifle`] 		 = {['name'] = 'weapon_marksmanrifle', 	 	['label'] = 'Fusil à lunette', 			['emsreason'] = 'Arme Gros Calibre', ['weapontype'] = 'Sniper Rifle',	['ammotype'] = 'AMMO_SNIPER',			['damagereason'] = 'Abattu par un fusil de précision'},
	[`weapon_marksmanrifle_mk2`]	 = {['name'] = 'weapon_marksmanrifle_mk2',	['label'] = 'Fusil à lunette MK2',	    ['emsreason'] = 'Arme Gros Calibre', ['weapontype'] = 'Sniper Rifle',	['ammotype'] = 'AMMO_SNIPER',			['damagereason'] = 'Abattu par un fusil de précision'},
	[`weapon_remotesniper`] 		 = {['name'] = 'weapon_remotesniper', 	 	['label'] = 'Remote Sniper', 			['emsreason'] = 'Arme Gros Calibre', ['weapontype'] = 'Sniper Rifle',	['ammotype'] = 'AMMO_SNIPER_REMOTE',	['damagereason'] = 'Abattu par un fusil de précision'},

    -- Heavy Weapons
	[`weapon_rpg`] 					 = {['name'] = 'weapon_rpg', 			      	['label'] = 'RPG', 						['emsreason'] = 'Explosion', ['weapontype'] = 'Heavy Weapons',	['ammotype'] = 'AMMO_RPG',				['damagereason'] = 'Abattu par une explosion'},
	[`weapon_grenadelauncher`] 		 = {['name'] = 'weapon_grenadelauncher', 	  	['label'] = 'Lance-Grenades', 		['emsreason'] = 'Explosion', ['weapontype'] = 'Heavy Weapons',	['ammotype'] = 'AMMO_GRENADELAUNCHER',	['damagereason'] = 'Abattu par une explosion'},
	[`weapon_grenadelauncher_smoke`] = {['name'] = 'weapon_grenadelauncher_smoke',	['label'] = 'Lance-Grenades Fumigènes',	['emsreason'] = 'Explosion', ['weapontype'] = 'Heavy Weapons',	['ammotype'] = 'AMMO_GRENADELAUNCHER',	['damagereason'] = 'Abattu par une explosion'},
	[`weapon_minigun`] 				 = {['name'] = 'weapon_minigun', 		      	['label'] = 'Minigun', 					['emsreason'] = 'Arme Gros Calibre', ['weapontype'] = 'Heavy Weapons',	['ammotype'] = 'AMMO_MINIGUN',			['damagereason'] = 'Abattu par une explosion'},
	[`weapon_firework`] 			 = {['name'] = 'weapon_firework', 		 	  	['label'] = 'Lanceur Pyrotechnique', 		['emsreason'] = 'Explosion', ['weapontype'] = 'Heavy Weapons',	['ammotype'] = nil,						['damagereason'] = 'Abattu par une explosion'},
	[`weapon_railgun`] 				 = {['name'] = 'weapon_railgun', 		 	  	['label'] = 'Fusil à Impulsion', 					['emsreason'] = 'Explosion', ['weapontype'] = 'Heavy Weapons',	['ammotype'] = nil,						['damagereason'] = 'Abattu par une explosion'},
	[`weapon_railgunxm3`]			 = {['name'] = 'weapon_railgunxm3',				['label'] = 'Fusil à Impulsion XM3',				['emsreason'] = 'Explosion', ['weapontype'] = 'Heavy Weapons',	['ammotype'] = nil,						['damagereason'] = 'Abattu par une explosion'},
	[`weapon_hominglauncher`] 		 = {['name'] = 'weapon_hominglauncher', 	 	['label'] = 'Lance-Missiles', 			['emsreason'] = 'Explosion', ['weapontype'] = 'Heavy Weapons',	['ammotype'] = 'AMMO_STINGER',			['damagereason'] = 'Abattu par une explosion'},
	[`weapon_compactlauncher`] 		 = {['name'] = 'weapon_compactlauncher',  	  	['label'] = 'Lance-Grenades Compact', 		['emsreason'] = 'Explosion', ['weapontype'] = 'Heavy Weapons',	['ammotype'] = nil,						['damagereason'] = 'Abattu par une explosion'},
	[`weapon_rayminigun`]			 = {['name'] = 'weapon_rayminigun', 		 	['label'] = 'Minigun Laser',		        ['emsreason'] = 'Explosion', ['weapontype'] = 'Heavy Weapons',	['ammotype'] = 'AMMO_MINIGUN',			['damagereason'] = 'Abattu par une explosion'},
    [`weapon_emplauncher`] 			 = {['name'] = 'weapon_emplauncher', 			['label'] = 'Lance-Grenades IEM', 			['emsreason'] = 'Explosion', ['weapontype'] = 'Heavy Weapons',	['ammotype'] = 'AMMO_EMPLAUNCHER',		['damagereason'] = 'Mort'},

    -- Throwables
	[`weapon_grenade`] 		        = {['name'] = 'weapon_grenade', 		['label'] = 'Grenade', 			['emsreason'] = 'Explosion', ['weapontype'] = 'Throwable',	['ammotype'] = nil,				['damagereason'] = 'Abattu par une explosion'},
	[`weapon_bzgas`] 		        = {['name'] = 'weapon_bzgas', 			['label'] = 'Gaz BZ', 			['emsreason'] = 'Gaz', ['weapontype'] = 'Throwable',	['ammotype'] = nil,				['damagereason'] = 'Mort'},
	[`weapon_molotov`] 		        = {['name'] = 'weapon_molotov', 		['label'] = 'Molotov', 			['emsreason'] = 'Brûlure', ['weapontype'] = 'Throwable',	['ammotype'] = nil,				['damagereason'] = 'Torched / Flambeed / Barbecued'},
	[`weapon_stickybomb`] 	        = {['name'] = 'weapon_stickybomb', 	    ['label'] = 'C4', 				['emsreason'] = 'Explosion', ['weapontype'] = 'Throwable',	['ammotype'] = nil,				['damagereason'] = 'Abattu par une explosion'},
	[`weapon_proxmine`] 	        = {['name'] = 'weapon_proxmine', 		['label'] = 'Mine de Proximité', ['emsreason'] = 'Explosion', ['weapontype'] = 'Throwable',	['ammotype'] = nil,				['damagereason'] = 'Abattu par une explosion'},
	[`weapon_snowball`] 	        = {['name'] = 'weapon_snowball', 		['label'] = 'Boule de Neige', 		['emsreason'] = 'Arme Contendante', ['weapontype'] = 'Throwable',	['ammotype'] = nil,				['damagereason'] = 'Mort'},
	[`weapon_pipebomb`] 	        = {['name'] = 'weapon_pipebomb', 		['label'] = 'Pipe Bomb', 		['emsreason'] = 'Explosion', ['weapontype'] = 'Throwable',	['ammotype'] = nil,				['damagereason'] = 'Abattu par une explosion'},
	[`weapon_ball`] 		        = {['name'] = 'weapon_ball', 			['label'] = 'Balle', 			['emsreason'] = 'Arme Contendante', ['weapontype'] = 'Throwable',	['ammotype'] = 'AMMO_BALL',		['damagereason'] = 'Mort'},
	[`weapon_smokegrenade`]         = {['name'] = 'weapon_smokegrenade', 	['label'] = 'Grenade Fumigène', 	['emsreason'] = 'Gaz', ['weapontype'] = 'Throwable',	['ammotype'] = nil,				['damagereason'] = 'Mort'},
	[`weapon_flare`] 		        = {['name'] = 'weapon_flare', 			['label'] = 'Fusée éclairante', 	['emsreason'] = 'Brûlure', ['weapontype'] = 'Throwable',	['ammotype'] = 'AMMO_FLARE',	['damagereason'] = 'Mort'},

    -- Miscellaneous
	[`weapon_petrolcan`] 			= {['name'] = 'weapon_petrolcan', 		 	['label'] = 'Bidon d\'Essence', 				['emsreason'] = 'Objet Contondant', ['weapontype'] = 'Miscellaneous',	['ammotype'] = 'AMMO_PETROLCAN',		['damagereason'] = 'Mort'},
	[`gadget_parachute`] 			= {['name'] = 'gadget_parachute', 		 	['label'] = 'Parachute', 				['emsreason'] = 'Chute', ['weapontype'] = 'Miscellaneous',	['ammotype'] = nil,						['damagereason'] = 'Mort'},
	[`weapon_fireextinguisher`] 	= {['name'] = 'weapon_fireextinguisher',	['label'] = 'Extincteur',		['emsreason'] = 'Objet Contondant', ['weapontype'] = 'Miscellaneous',	['ammotype'] = nil,						['damagereason'] = 'Mort'},
	[`weapon_hazardcan`]			= {['name'] = 'weapon_hazardcan',			['label'] = 'Bidon de Produits Toxiques',			    ['emsreason'] = 'Objet Contondant', ['weapontype'] = 'Miscellaneous',	['ammotype'] = 'AMMO_PETROLCAN',		['damagereason'] = 'Mort'},
    [`weapon_fertilizercan`]		= {['name'] = 'weapon_fertilizercan',		['label'] = 'Bidon de Fertilisant',			['emsreason'] = 'Objet Contondant', ['weapontype'] = 'Miscellaneous',	['ammotype'] = 'AMMO_FERTILIZERCAN',	['damagereason'] = 'Mort'},
	[`weapon_barbed_wire`]			= {['name'] = 'weapon_barbed_wire',			['label'] = 'Fil Barbelé',				['emsreason'] = 'Fil Barbelé', ['weapontype'] = 'Miscellaneous',	['ammotype'] = nil,						['damagereason'] = 'Emmêlé dans du barbelé'},
	[`weapon_drowning`]				= {['name'] = 'weapon_drowning',			['label'] = 'Noyade',					['emsreason'] = 'Noyade', ['weapontype'] = 'Miscellaneous',	['ammotype'] = nil,						['damagereason'] = 'Mort'},
	[`weapon_drowning_in_vehicle`]	= {['name'] = 'weapon_drowning_in_vehicle',	['label'] = 'Noyade en Véhicle',	['emsreason'] = 'Noyade', ['weapontype'] = 'Miscellaneous',	['ammotype'] = nil,						['damagereason'] = 'Mort'},
	[`weapon_bleeding`]				= {['name'] = 'weapon_bleeding',			['label'] = 'Saignement',					['emsreason'] = 'Saignement', ['weapontype'] = 'Miscellaneous',	['ammotype'] = nil,						['damagereason'] = 'Mort par saignement'},
	[`weapon_electric_fence`]		= {['name'] = 'weapon_electric_fence',		['label'] = 'Barrière Electrique',			['emsreason'] = 'Electrocution', ['weapontype'] = 'Miscellaneous',	['ammotype'] = nil,						['damagereason'] = 'Electrocuté'},
	[`weapon_explosion`]			= {['name'] = 'weapon_explosion',			['label'] = 'Explosion',				['emsreason'] = 'Explosion', ['weapontype'] = 'Miscellaneous',	['ammotype'] = nil,						['damagereason'] = 'Abattu par une explosion'},
	[`weapon_fall`]					= {['name'] = 'weapon_fall',				['label'] = 'Chute',						['emsreason'] = 'Chute', ['weapontype'] = 'Miscellaneous',	['ammotype'] = nil,						['damagereason'] = 'Chute'},
	[`weapon_exhaustion`]			= {['name'] = 'weapon_exhaustion',			['label'] = 'Fatigue',				['emsreason'] = 'Fatigue', ['weapontype'] = 'Miscellaneous',	['ammotype'] = nil,						['damagereason'] = 'Mort'},
	[`weapon_hit_by_water_cannon`]	= {['name'] = 'weapon_hit_by_water_cannon',	['label'] = 'Canon à Eau',				['emsreason'] = 'Canon à Eau', ['weapontype'] = 'Miscellaneous',	['ammotype'] = nil,						['damagereason'] = 'Mort'},
	[`weapon_rammed_by_car`]		= {['name'] = 'weapon_rammed_by_car',		['label'] = 'Percuté par un Véhicule',			['emsreason'] = 'Choc Violent', ['weapontype'] = 'Miscellaneous',	['ammotype'] = nil,						['damagereason'] = 'Percuté par un Véhicule'},
	[`weapon_run_over_by_car`]		= {['name'] = 'weapon_run_over_by_car',		['label'] = 'Ecrasé par un Véhicule',		['emsreason'] = 'Choc Violent', ['weapontype'] = 'Miscellaneous',	['ammotype'] = nil,						['damagereason'] = 'Ecrasé par un Véhicule'},
	[`weapon_heli_crash`]			= {['name'] = 'weapon_heli_crash',			['label'] = 'Crash d\'Hélicoptère',				['emsreason'] = 'Choc Violent', ['weapontype'] = 'Miscellaneous',	['ammotype'] = nil,						['damagereason'] = 'Crash d\'hélicoptère'},
	[`weapon_fire`]					= {['name'] = 'weapon_fire',				['label'] = 'Feu',						['emsreason'] = 'Brûlure', ['weapontype'] = 'Miscellaneous',	['ammotype'] = nil,						['damagereason'] = 'Brulé vif'},

	-- Animals
    [`weapon_animal`]               = {['name'] = 'weapon_animal',	['label'] = 'Animal',	['emsreason'] = 'Griffures', ['weapontype'] = 'Animals',	['ammotype'] = nil,	['damagereason'] = 'Mordu'},
    [`weapon_cougar`]               = {['name'] = 'weapon_cougar',	['label'] = 'Cougar',	['emsreason'] = 'Griffures', ['weapontype'] = 'Animals',	['ammotype'] = nil,	['damagereason'] = 'Mordu'},
}